-- MySQL Script generated by MySQL Workbench
-- Thu Oct 28 10:07:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SocialCity
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SocialCity
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SocialCity` DEFAULT CHARACTER SET utf8 ;
USE `SocialCity` ;

-- -----------------------------------------------------
-- Table `SocialCity`.`FAVORITOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialCity`.`FAVORITOS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Direccion` VARCHAR(50) NOT NULL,
  `Puntuacion` DECIMAL(1,1) NOT NULL,
  `Telefono` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialCity`.`ALARMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialCity`.`ALARMA` (
  `N.Alarma` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Fecha` VARCHAR(10) NOT NULL,
  `Hora` VARCHAR(5) NOT NULL,
  `Descripción` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`N.Alarma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialCity`.`PERFIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialCity`.`PERFIL` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Sexo` VARCHAR(6) NULL,
  `Edad` VARCHAR(2) NULL,
  `EstadoCivil` VARCHAR(20) NULL,
  `RamaProfesional` VARCHAR(45) NULL,
  `Intereses` VARCHAR(100) NULL,
  `FAVORITOS_ID` INT NOT NULL,
  `ALARMA_N.Alarma` INT NOT NULL,
  PRIMARY KEY (`ID`, `FAVORITOS_ID`, `ALARMA_N.Alarma`),
  INDEX `fk_PERFIL_FAVORITOS1_idx` (`FAVORITOS_ID` ASC) VISIBLE,
  INDEX `fk_PERFIL_ALARMA1_idx` (`ALARMA_N.Alarma` ASC) VISIBLE,
  CONSTRAINT `fk_PERFIL_FAVORITOS1`
    FOREIGN KEY (`FAVORITOS_ID`)
    REFERENCES `SocialCity`.`FAVORITOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERFIL_ALARMA1`
    FOREIGN KEY (`ALARMA_N.Alarma`)
    REFERENCES `SocialCity`.`ALARMA` (`N.Alarma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialCity`.`CLIENTES_HABITUALES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialCity`.`CLIENTES_HABITUALES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) NOT NULL,
  `HoraAproximada` VARCHAR(5) NOT NULL,
  `Edad` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialCity`.`DIRECCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialCity`.`DIRECCION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Zona` VARCHAR(20) NOT NULL,
  `Calle` VARCHAR(50) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialCity`.`RESTAURANTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialCity`.`RESTAURANTE` (
  `Nombre` VARCHAR(50) NOT NULL,
  `Capacidad` VARCHAR(30) NOT NULL,
  `Ocupacion` VARCHAR(3) NOT NULL,
  `Puntuacion` DECIMAL(1,1) NOT NULL,
  `Carta` VARCHAR(5000) NULL,
  `Horario` VARCHAR(1000) NOT NULL,
  `CLIENTES_HABITUALES_ID1` INT NOT NULL,
  `DIRECCION_ID` INT NOT NULL,
  PRIMARY KEY (`Nombre`, `CLIENTES_HABITUALES_ID1`, `DIRECCION_ID`),
  INDEX `fk_RESTAURANTE_CLIENTES_HABITUALES2_idx` (`CLIENTES_HABITUALES_ID1` ASC) VISIBLE,
  INDEX `fk_RESTAURANTE_DIRECCION1_idx` (`DIRECCION_ID` ASC) VISIBLE,
  CONSTRAINT `fk_RESTAURANTE_CLIENTES_HABITUALES2`
    FOREIGN KEY (`CLIENTES_HABITUALES_ID1`)
    REFERENCES `SocialCity`.`CLIENTES_HABITUALES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESTAURANTE_DIRECCION1`
    FOREIGN KEY (`DIRECCION_ID`)
    REFERENCES `SocialCity`.`DIRECCION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialCity`.`USUARIO_valora_RESTAURANTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialCity`.`USUARIO_valora_RESTAURANTE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `RESTAURANTE_Nombre` VARCHAR(50) NOT NULL,
  `RESTAURANTE_CLIENTES_HABITUALES_ID1` INT NOT NULL,
  `Nota` INT NOT NULL,
  PRIMARY KEY (`ID`, `RESTAURANTE_Nombre`, `RESTAURANTE_CLIENTES_HABITUALES_ID1`),
  INDEX `fk_USUARIO_valora_RESTAURANTE_RESTAURANTE1_idx` (`RESTAURANTE_Nombre` ASC, `RESTAURANTE_CLIENTES_HABITUALES_ID1` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_valora_RESTAURANTE_RESTAURANTE1`
    FOREIGN KEY (`RESTAURANTE_Nombre` , `RESTAURANTE_CLIENTES_HABITUALES_ID1`)
    REFERENCES `SocialCity`.`RESTAURANTE` (`Nombre` , `CLIENTES_HABITUALES_ID1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialCity`.`BAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialCity`.`BAR` (
  `Nombre` VARCHAR(50) NOT NULL,
  `Capacidad` VARCHAR(30) NOT NULL,
  `Ocupacion` VARCHAR(30) NOT NULL,
  `Puntuacion` DECIMAL(1,1) NOT NULL,
  `Horario` VARCHAR(1000) NOT NULL,
  `DIRECCION_ID` INT NOT NULL,
  `CLIENTES_HABITUALES_ID` INT NOT NULL,
  PRIMARY KEY (`Nombre`, `DIRECCION_ID`, `CLIENTES_HABITUALES_ID`),
  INDEX `fk_BAR_DIRECCION1_idx` (`DIRECCION_ID` ASC) VISIBLE,
  INDEX `fk_BAR_CLIENTES_HABITUALES1_idx` (`CLIENTES_HABITUALES_ID` ASC) VISIBLE,
  CONSTRAINT `fk_BAR_DIRECCION1`
    FOREIGN KEY (`DIRECCION_ID`)
    REFERENCES `SocialCity`.`DIRECCION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BAR_CLIENTES_HABITUALES1`
    FOREIGN KEY (`CLIENTES_HABITUALES_ID`)
    REFERENCES `SocialCity`.`CLIENTES_HABITUALES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialCity`.`USUARIO_valora_BAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialCity`.`USUARIO_valora_BAR` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `BAR_Nombre` VARCHAR(50) NOT NULL,
  `BAR_DIRECCION_ID` INT NOT NULL,
  `BAR_CLIENTES_HABITUALES_ID` INT NOT NULL,
  `Nota` INT NOT NULL,
  PRIMARY KEY (`ID`, `BAR_Nombre`, `BAR_DIRECCION_ID`, `BAR_CLIENTES_HABITUALES_ID`),
  INDEX `fk_USUARIO_valora_BAR_BAR1_idx` (`BAR_Nombre` ASC, `BAR_DIRECCION_ID` ASC, `BAR_CLIENTES_HABITUALES_ID` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_valora_BAR_BAR1`
    FOREIGN KEY (`BAR_Nombre` , `BAR_DIRECCION_ID` , `BAR_CLIENTES_HABITUALES_ID`)
    REFERENCES `SocialCity`.`BAR` (`Nombre` , `DIRECCION_ID` , `CLIENTES_HABITUALES_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialCity`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialCity`.`USUARIO` (
  `Alias` VARCHAR(50) NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `Apellidos` VARCHAR(30) NOT NULL,
  `Clave` VARCHAR(30) NOT NULL,
  `PERFIL_ID` INT NOT NULL,
  `USUARIO_valora_RESTAURANTE_ID` INT NOT NULL,
  `USUARIO_valora_BAR_ID` INT NOT NULL,
  PRIMARY KEY (`Alias`, `PERFIL_ID`, `USUARIO_valora_RESTAURANTE_ID`, `USUARIO_valora_BAR_ID`),
  INDEX `fk_USUARIO_PERFIL_idx` (`PERFIL_ID` ASC) VISIBLE,
  INDEX `fk_USUARIO_USUARIO_valora_RESTAURANTE1_idx` (`USUARIO_valora_RESTAURANTE_ID` ASC) VISIBLE,
  INDEX `fk_USUARIO_USUARIO_valora_BAR1_idx` (`USUARIO_valora_BAR_ID` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_PERFIL`
    FOREIGN KEY (`PERFIL_ID`)
    REFERENCES `SocialCity`.`PERFIL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_USUARIO_valora_RESTAURANTE1`
    FOREIGN KEY (`USUARIO_valora_RESTAURANTE_ID`)
    REFERENCES `SocialCity`.`USUARIO_valora_RESTAURANTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_USUARIO_valora_BAR1`
    FOREIGN KEY (`USUARIO_valora_BAR_ID`)
    REFERENCES `SocialCity`.`USUARIO_valora_BAR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialCity`.`ME_GUSTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialCity`.`ME_GUSTA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Alias_USUARIO` VARCHAR(50) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialCity`.`COMENTARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialCity`.`COMENTARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(1000) NOT NULL,
  `RESTAURANTE_Nombre` VARCHAR(50) NOT NULL,
  `BAR_Nombre` VARCHAR(50) NOT NULL,
  `ME_GUSTA_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `RESTAURANTE_Nombre`, `BAR_Nombre`, `ME_GUSTA_ID`),
  INDEX `fk_COMENTARIO_RESTAURANTE1_idx` (`RESTAURANTE_Nombre` ASC) VISIBLE,
  INDEX `fk_COMENTARIO_BAR1_idx` (`BAR_Nombre` ASC) VISIBLE,
  INDEX `fk_COMENTARIO_ME_GUSTA1_idx` (`ME_GUSTA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_COMENTARIO_RESTAURANTE1`
    FOREIGN KEY (`RESTAURANTE_Nombre`)
    REFERENCES `SocialCity`.`RESTAURANTE` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMENTARIO_BAR1`
    FOREIGN KEY (`BAR_Nombre`)
    REFERENCES `SocialCity`.`BAR` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMENTARIO_ME_GUSTA1`
    FOREIGN KEY (`ME_GUSTA_ID`)
    REFERENCES `SocialCity`.`ME_GUSTA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialCity`.`USUARIO_hace_COMENTARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialCity`.`USUARIO_hace_COMENTARIO` (
  `USUARIO_Alias` VARCHAR(50) NOT NULL,
  `USUARIO_PERFIL_ID` INT NOT NULL,
  `COMENTARIO_ID` INT NOT NULL,
  PRIMARY KEY (`USUARIO_Alias`, `USUARIO_PERFIL_ID`, `COMENTARIO_ID`),
  INDEX `fk_USUARIO_has_COMENTARIO_COMENTARIO1_idx` (`COMENTARIO_ID` ASC) VISIBLE,
  INDEX `fk_USUARIO_has_COMENTARIO_USUARIO1_idx` (`USUARIO_Alias` ASC, `USUARIO_PERFIL_ID` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_has_COMENTARIO_USUARIO1`
    FOREIGN KEY (`USUARIO_Alias` , `USUARIO_PERFIL_ID`)
    REFERENCES `SocialCity`.`USUARIO` (`Alias` , `PERFIL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_has_COMENTARIO_COMENTARIO1`
    FOREIGN KEY (`COMENTARIO_ID`)
    REFERENCES `SocialCity`.`COMENTARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
